---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hema
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hema
  template:
    metadata:
      labels:
        app: hema
    spec:
      containers:
      - name: hema
        image: hemakumariperumandla/docker-project-may:zomatov1
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hema-service
spec:
  selector:
    app: hema
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
